NRE when starting the game in Editor. #5243
NRE when starting the game in Editor. #5243

Seems that some jobs are missing their Head of department.  However, it seems to appear at random.  More investigation to come.

NullReferenceException: Object reference not set to an instance of an object
System.Collections.Generic.LargeArrayBuilder1[T].AddRange (System.Collections.Generic.IEnumerable1[T] items) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Collections.Generic.SparseArrayBuilder1[T].AddRange (System.Collections.Generic.IEnumerable1[T] items) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Collections.Generic.SparseArrayBuilder1[T].ReserveOrAdd (System.Collections.Generic.IEnumerable1[T] items) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable+SelectManySingleSelectorIterator2[TSource,TResult].ToArray () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0) System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
JobAllocator.DetermineJobs (System.Collections.Generic.IEnumerable`1[T] players) (at Assets/Scripts/Managers/JobAllocator.cs:39)
GameModes.GameMode.StartRound () (at Assets/Scripts/Systems/GameModes/GameMode.cs:319)
GameManager+d__23.MoveNext () (at Assets/Scripts/Managers/GameManager.GameMode.cs:152)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at :0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)