Correction of a frequent NullReferenceException on Server.
Correction of a frequent NullReferenceException on Server.
The correction also better logs the real cause.

NullReferenceException: Object reference not set to an instance of an object
  at Validations.CanApply (PlayerScript playerScript, UnityEngine.GameObject target, NetworkSide side, System.Boolean allowSoftCrit, ReachRange reachRange, System.Nullable`1[T] targetVector, RegisterTile targetRegisterTile) [0x000ca] in <b0f20000d54a4b7c90f0e64314ff80d4>:0
  at PlayerNetworkActions.CmdRequestDisarm (UnityEngine.GameObject playerToDisarm) [0x00000] in <b0f20000d54a4b7c90f0e64314ff80d4>:0
  at PlayerNetworkActions.InvokeCmdCmdRequestDisarm (Mirror.NetworkBehaviour obj, Mirror.NetworkReader reader) [0x00022] in <b0f20000d54a4b7c90f0e64314ff80d4>:0
  at Mirror.NetworkBehaviour.InvokeHandlerDelegate (System.Int32 cmdHash, Mirror.MirrorInvokeType invokeType, Mirror.NetworkReader reader) [0x00019] in <b7d799db5089484da70f2beb1e5a8dc6>:0
  at Mirror.NetworkIdentity.HandleRemoteCall (System.Int32 componentIndex, System.Int32 functionHash, Mirror.MirrorInvokeType invokeType, Mirror.NetworkReader reader) [0x00069] in <b7d799db5089484da70f2beb1e5a8dc6>:0
  at Mirror.NetworkIdentity.HandleCommand (System.Int32 componentIndex, System.Int32 cmdHash, Mirror.NetworkReader reader) [0x00000] in <b7d799db5089484da70f2beb1e5a8dc6>:0