Server-Side error fixed.
Correction of a missing sprite in shuttle_status.psd.  The enum had a new status "To the station teleporter" added in the middle of the enum but the sprite sheet didn't account for that.

IndexOutOfRangeException: Index was outside the bounds of the array.
NetSpriteImage.set_Value (System.String value) (at /github/workspace/UnityProject/Assets/Scripts/UI/Net/Elements/NetSpriteImage.cs:37)
NetUIElement`1[T].SetValueServer (T value) (at /github/workspace/UnityProject/Assets/Scripts/UI/Net/Elements/NetUIElement.cs:85)
NetSpriteImage.SetComplicatedValue (System.String spriteSheet, System.Int32 spriteOffset) (at /github/workspace/UnityProject/Assets/Scripts/UI/Net/Elements/NetSpriteImage.cs:55)
GUI_Comms+<WaitForProvider>d__19.MoveNext () (at /github/workspace/UnityProject/Assets/Scripts/UI/Comms/GUI_Comms.cs:82)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /home/builduser/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)