Equipment load fix and ConnectedPlayers update fix
First exception: UpdateConnectPlayersMessage.cs:32
InvalidOperationException: Collection was modified; enumeration operation may not execute.

Cause: The dictionary was being modified while it was being iterated through. Fix: Collected all of the changes and performed them at the end

Second Exception: Equipment.cs:187
NRE

Cause: If for any reason clothfactory returns a null object this will occur.
Fix: Added a LogError so the root cause can be investigated if some improper usage of equipment player load out is being used.